# Generated by Django 4.2.3 on 2023-07-15 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Name', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Registration',
            fields=[
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(default='admin', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1_ans', models.IntegerField()),
                ('Q2_ans', models.IntegerField()),
                ('Q3_ans', models.IntegerField()),
                ('Q4_ans', models.CharField(max_length=500)),
                ('Q5_ans', models.CharField(max_length=500)),
                ('Event_ans_id_fk', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1', models.CharField(max_length=500)),
                ('Q2', models.CharField(max_length=500)),
                ('Q3', models.CharField(max_length=500)),
                ('Q4', models.CharField(max_length=500)),
                ('Q5', models.CharField(max_length=500)),
                ('Event_id_fk', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
        ),
    ]
