# Generated by Django 3.2.13 on 2023-12-13 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrpfDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrpfUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=13)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ThreatInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('signature', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green')], max_length=20)),
                ('bgcolor', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green')], max_length=20)),
                ('ref_links', models.TextField()),
                ('playbooks', models.ManyToManyField(to='api.Playbook')),
            ],
        ),
        migrations.CreateModel(
            name='LogLines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('crpf_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crpfdevice')),
                ('crpf_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crpfunit')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.threatinfo')),
            ],
        ),
        migrations.AddField(
            model_name='crpfdevice',
            name='crpf_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crpfunit'),
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Resolved', 'Resolved'), ('Unresolved', 'Unresolved'), ('Ignored', 'Ignored')], max_length=20)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('log_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loglines')),
            ],
        ),
    ]
