# Generated by Django 3.2.13 on 2023-12-13 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_questions',
            name='Event_id_fk',
        ),
        migrations.RemoveField(
            model_name='feedback_answers',
            name='Event_ans_id_fk',
        ),
        migrations.DeleteModel(
            name='User_Registration',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Event_Questions',
        ),
        migrations.DeleteModel(
            name='Feedback_Answers',
        ),
    ]
