# Generated by Django 3.2.13 on 2023-12-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_loglines_threat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loglines',
            name='threat',
        ),
        migrations.AddField(
            model_name='loglines',
            name='threat',
            field=models.ManyToManyField(null=True, to='api.ThreatInfo'),
        ),
    ]
