# Generated by Django 3.2.13 on 2023-12-13 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20231213_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loglines',
            name='threat',
        ),
        migrations.AddField(
            model_name='loglines',
            name='threat',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='api.threatinfo'),
            preserve_default=False,
        ),
    ]
