# Generated by Django 4.2.3 on 2023-07-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_answers',
            name='Q1_ans',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback_answers',
            name='Q2_ans',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback_answers',
            name='Q3_ans',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback_answers',
            name='Q4_ans',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='feedback_answers',
            name='Q5_ans',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
