# Generated by Django 3.2.13 on 2023-12-13 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231213_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loglines',
            name='threat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.threatinfo'),
        ),
    ]
