# Generated by Django 4.2.3 on 2023-07-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_event_questions_event_id_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
