# Generated by Django 4.2.3 on 2023-07-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_questions',
            old_name='Q5',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='feedback_answers',
            name='Q5_ans',
        ),
        migrations.AddField(
            model_name='feedback_answers',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
