# Generated by Django 3.2.13 on 2023-12-14 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_alerts_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='crpfdevice',
            name='color',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('server', 'Server'), ('desktop', 'Desktop')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crpfdevice',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='crpfunit',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='loglines',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='playbook',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='threatinfo',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='threatinfo',
            name='bgcolor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='threatinfo',
            name='color',
            field=models.CharField(max_length=20),
        ),
    ]
