# Generated by Django 3.2.13 on 2023-12-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20231214_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='updation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
