# Generated by Django 4.2.3 on 2023-07-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_q5_event_questions_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_Letter_Subscription',
            fields=[
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('interest', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
