# Generated by Django 4.2.3 on 2023-07-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_news_letter_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_letter_subscription',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
