# Generated by Django 3.2.13 on 2023-12-14 06:02

import colorfield.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alerts_updation_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crpfdevice',
            old_name='color',
            new_name='device_type',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='updation_time',
        ),
        migrations.AddField(
            model_name='alerts',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='threatinfo',
            name='bgcolor',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='threatinfo',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None, verbose_name='Color'),
        ),
    ]
