# Generated by Django 3.2.13 on 2023-12-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20231214_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('WaitList', 'WaitList')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
