# Generated by Django 4.2.3 on 2023-07-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_news_letter_subscription_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_letter_subscription',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news_letter_subscription',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
