# Generated by Django 3.2.13 on 2023-12-14 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_playbook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='crpfunit',
            name='unit_image',
            field=models.FileField(null=True, upload_to='crpf_unit_pictures/'),
        ),
        migrations.CreateModel(
            name='Profile_pic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_pic', models.FileField(null=True, upload_to='profile_pictures/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
