# Generated by Django 3.2.13 on 2023-12-14 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20231214_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_pic',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile_pic',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
