# Generated by Django 3.2.13 on 2023-12-15 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_profile_pic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='crpfunit',
            name='mail_address',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.CreateModel(
            name='Crpf_Device_Agent_Repo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_key', models.TextField()),
                ('code', models.TextField()),
                ('version', models.TextField()),
                ('crpf_device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crpfdevice')),
            ],
        ),
    ]
