# Generated by Django 3.2.13 on 2023-12-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20231215_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crpf_device_agent_repo',
            name='access_key',
            field=models.TextField(unique=True),
        ),
    ]
