# Generated by Django 5.0 on 2023-12-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_crpf_device_agent_repo_access_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatinfo',
            name='remediation',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
