# Generated by Django 3.2.13 on 2023-12-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20231219_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatinfo',
            name='categories',
            field=models.ManyToManyField(default=None, related_name='threats', to='api.Category'),
        ),
    ]
