# Generated by Django 3.2.13 on 2023-12-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_threatinfo_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatinfo',
            name='signature',
            field=models.CharField(max_length=500),
        ),
    ]
