# Generated by Django 3.2.13 on 2023-12-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20231219_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatinfo',
            name='remediation',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
