# Generated by Django 3.2.13 on 2023-12-20 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_threatinfo_remediation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alerts')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.threatinfo')),
            ],
        ),
    ]
