# Generated by Django 3.2.13 on 2023-12-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatinfo',
            name='remediation',
            field=models.FileField(null=True, upload_to='remediations/'),
        ),
    ]
