# Generated by Django 5.1.3 on 2024-11-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_threatinfo_remediation'),
        ('api', '0023_alter_threatinfo_remediation'),
    ]

    operations = [
    ]
