# Generated by Django 4.2.5 on 2023-09-24 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='log_file_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
