# Generated by Django 4.2.7 on 2023-12-12 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Resolved', 'Resolved'), ('Unresolved', 'Unresolved'), ('Ignored', 'Ignored')], max_length=20)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CrpfDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CrpfUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='LogLines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('crpf_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_analyzer.crpfdevice')),
                ('crpf_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_analyzer.crpfunit')),
            ],
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ThreatInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('signature', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green')], max_length=20)),
                ('ref_links', models.TextField()),
                ('playbook_if', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_analyzer.playbook')),
            ],
        ),
        migrations.DeleteModel(
            name='LogEntry',
        ),
        migrations.AddField(
            model_name='loglines',
            name='threat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_analyzer.threatinfo'),
        ),
        migrations.AddField(
            model_name='crpfdevice',
            name='crpf_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_analyzer.crpfunit'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='log_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_analyzer.loglines'),
        ),
    ]
